/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated.invoices'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedSellersRouteImport } from './routes/_authenticated.sellers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated.whatsapp'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated.customers.index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated.customers.$customerId'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated.inventory.index'
import { Route as AuthenticatedInventoryAddRouteImport } from './routes/_authenticated.inventory.add'
import { Route as AuthenticatedRepairsIndexRouteImport } from './routes/_authenticated.repairs.index'
import { Route as AuthenticatedRepairsRepairIdRouteImport } from './routes/_authenticated.repairs.$repairId'
import { Route as AuthenticatedInventoryPhoneIdIndexRouteImport } from './routes/_authenticated.inventory.$phoneId.index'
import { Route as AuthenticatedInventoryPhoneIdEditRouteImport } from './routes/_authenticated.inventory.$phoneId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellersRoute = AuthenticatedSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAddRoute =
  AuthenticatedInventoryAddRouteImport.update({
    id: '/inventory/add',
    path: '/inventory/add',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepairsIndexRoute =
  AuthenticatedRepairsIndexRouteImport.update({
    id: '/repairs/',
    path: '/repairs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepairsRepairIdRoute =
  AuthenticatedRepairsRepairIdRouteImport.update({
    id: '/repairs/$repairId',
    path: '/repairs/$repairId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryPhoneIdIndexRoute =
  AuthenticatedInventoryPhoneIdIndexRouteImport.update({
    id: '/inventory/$phoneId/',
    path: '/inventory/$phoneId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryPhoneIdEditRoute =
  AuthenticatedInventoryPhoneIdEditRouteImport.update({
    id: '/inventory/$phoneId/edit',
    path: '/inventory/$phoneId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sellers': typeof AuthenticatedSellersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/inventory/add': typeof AuthenticatedInventoryAddRoute
  '/repairs/$repairId': typeof AuthenticatedRepairsRepairIdRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/inventory/$phoneId/edit': typeof AuthenticatedInventoryPhoneIdEditRoute
  '/inventory/$phoneId/': typeof AuthenticatedInventoryPhoneIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sellers': typeof AuthenticatedSellersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/inventory/add': typeof AuthenticatedInventoryAddRoute
  '/repairs/$repairId': typeof AuthenticatedRepairsRepairIdRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/repairs': typeof AuthenticatedRepairsIndexRoute
  '/inventory/$phoneId/edit': typeof AuthenticatedInventoryPhoneIdEditRoute
  '/inventory/$phoneId': typeof AuthenticatedInventoryPhoneIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sellers': typeof AuthenticatedSellersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/inventory/add': typeof AuthenticatedInventoryAddRoute
  '/_authenticated/repairs/$repairId': typeof AuthenticatedRepairsRepairIdRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/repairs/': typeof AuthenticatedRepairsIndexRoute
  '/_authenticated/inventory/$phoneId/edit': typeof AuthenticatedInventoryPhoneIdEditRoute
  '/_authenticated/inventory/$phoneId/': typeof AuthenticatedInventoryPhoneIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/invoices'
    | '/profile'
    | '/reports'
    | '/sellers'
    | '/settings'
    | '/whatsapp'
    | '/customers/$customerId'
    | '/inventory/add'
    | '/repairs/$repairId'
    | '/customers/'
    | '/inventory/'
    | '/repairs/'
    | '/inventory/$phoneId/edit'
    | '/inventory/$phoneId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/invoices'
    | '/profile'
    | '/reports'
    | '/sellers'
    | '/settings'
    | '/whatsapp'
    | '/customers/$customerId'
    | '/inventory/add'
    | '/repairs/$repairId'
    | '/customers'
    | '/inventory'
    | '/repairs'
    | '/inventory/$phoneId/edit'
    | '/inventory/$phoneId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/sellers'
    | '/_authenticated/settings'
    | '/_authenticated/whatsapp'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/inventory/add'
    | '/_authenticated/repairs/$repairId'
    | '/_authenticated/customers/'
    | '/_authenticated/inventory/'
    | '/_authenticated/repairs/'
    | '/_authenticated/inventory/$phoneId/edit'
    | '/_authenticated/inventory/$phoneId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sellers': {
      id: '/_authenticated/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof AuthenticatedSellersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/add': {
      id: '/_authenticated/inventory/add'
      path: '/inventory/add'
      fullPath: '/inventory/add'
      preLoaderRoute: typeof AuthenticatedInventoryAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repairs/': {
      id: '/_authenticated/repairs/'
      path: '/repairs'
      fullPath: '/repairs/'
      preLoaderRoute: typeof AuthenticatedRepairsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repairs/$repairId': {
      id: '/_authenticated/repairs/$repairId'
      path: '/repairs/$repairId'
      fullPath: '/repairs/$repairId'
      preLoaderRoute: typeof AuthenticatedRepairsRepairIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/$phoneId/': {
      id: '/_authenticated/inventory/$phoneId/'
      path: '/inventory/$phoneId'
      fullPath: '/inventory/$phoneId/'
      preLoaderRoute: typeof AuthenticatedInventoryPhoneIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/$phoneId/edit': {
      id: '/_authenticated/inventory/$phoneId/edit'
      path: '/inventory/$phoneId/edit'
      fullPath: '/inventory/$phoneId/edit'
      preLoaderRoute: typeof AuthenticatedInventoryPhoneIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSellersRoute: typeof AuthenticatedSellersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedInventoryAddRoute: typeof AuthenticatedInventoryAddRoute
  AuthenticatedRepairsRepairIdRoute: typeof AuthenticatedRepairsRepairIdRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedRepairsIndexRoute: typeof AuthenticatedRepairsIndexRoute
  AuthenticatedInventoryPhoneIdEditRoute: typeof AuthenticatedInventoryPhoneIdEditRoute
  AuthenticatedInventoryPhoneIdIndexRoute: typeof AuthenticatedInventoryPhoneIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSellersRoute: AuthenticatedSellersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedInventoryAddRoute: AuthenticatedInventoryAddRoute,
  AuthenticatedRepairsRepairIdRoute: AuthenticatedRepairsRepairIdRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedRepairsIndexRoute: AuthenticatedRepairsIndexRoute,
  AuthenticatedInventoryPhoneIdEditRoute:
    AuthenticatedInventoryPhoneIdEditRoute,
  AuthenticatedInventoryPhoneIdIndexRoute:
    AuthenticatedInventoryPhoneIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
